### ISSUE TITLE
method 'get' should return by value instead of reference

### ISSUE THREAD

**Issue by tianpeng-li** [mohaps/lrucache11#14]
https://github.com/mohaps/lrucache11/blob/296b029305ea38da0c769666565e5fb197b0036b/LRUCache11.hpp#L138

for example:
Cache<int, type> cache(2);
cache.insert(1, t1);
type & rtn = cache.get(1);
cache.insert(2, t2);
cache.insert(3, t3);
--------
now, rtn will reffer to an object no longer exist.

**Comment by mohaps** [comment]
Added a getCopy() method and the current tryGet() method is also a safe alternative.

Added a comment to get() indicating that the validity window of the reference is only till next insert/delete. This is similar to front() on STL containers

**Comment by tianpeng-li** [comment]
the getCopy doesn't fix the problem in multi threading environment.
